### ISSUE TITLE
Kindly please provide image with PHP 7.1.x and MySQL 5.7.x

### ISSUE THREAD

**Issue by JanSichula** [appsvc/php#1]

**Comment by nickwalkmsft** [comment]
Hi @JanSichula,

Just to set expectations - we will continue to grow our list of "blessed" images, but providing a multitude of images with specific combinations/versions of platform software is not high on our priority list right now, and is one of the reasons we have enabled custom images.

You are free to crib from or inherit from any of our images - they are available on [Dockerhub](https://hub.docker.com/u/appsvc/) and on [Github](https://github.com/Azure-App-Service).

I will keep this open for now as it's good feedback into the kind of images we should provide.
