### ISSUE TITLE
Environment Variables are not exported properly in SSH terminal

### ISSUE THREAD

**Issue by blueelvis** [appsvc/php#20]
Hello,

The following piece of code does not export the Environment variables correctly -
```
# Get environment variables to show up in SSH session
eval $(printenv | awk -F= '{print "export " $1"="$2 }' >> /etc/profile)
```

In most of the cases, I see the following when logging into the container using SSH -
```
-bash: export: `-fpic': not a valid identifier
-bash: export: `-fpie': not a valid identifier
-bash: export: `-O2': not a valid identifier
-bash: export: `dpkg-dev': not a valid identifier
-bash: export: `g++': not a valid identifier
-bash: export: `libc-dev': not a valid identifier
-bash: export: `libpcre3-dev': not a valid identifier
-bash: export: `pkg-config': not a valid identifier
-bash: export: `-Wl,--hash-style': not a valid identifier
-bash: export: `528995BFEDFBA7191D46839EF9BA0ADA31CBD89E': not a valid identifier
-bash: export: `-fpic': not a valid identifier
-bash: export: `-fpie': not a valid identifier
-bash: export: `-O2': not a valid identifier
root@53583a8ec010:/home/site/wwwroot#
```

**Comment by blueelvis** [comment]
And there are also connection strings which contain the `=` symbol which causes the above code to export only partial connection string to the SSH environment. This is required in certain cases for tools like Drush...

**Comment by UpQuark** [comment]
Was there any resolution to this? I see this exact behavior on Azure Web App For Containers with environment variables.

**Comment by blueelvis** [comment]
@UpQuark - I forgot updating this issue back but I was able to resolve this pretty closely. Take a look here (I wrote it) - https://omgdebugging.com/2018/10/05/how-to-export-environment-variables-in-azure-web-app-for-containers/

You would have to add (Read post for other considerations) -
```
# Get environment variables to show up in SSH session
eval $(printenv | awk -F= '{print "export " "\""$1"\"""=""\""$2"\"" }' >> /etc/profile)
```

Let me know if you have any issues even after this.

**Comment by UpQuark** [comment]
Thanks @blueelvis. As it turns out, I had a similar issue where environment variables with spaces were coming out of my build script un-escaped (Azure didn't seem to respect the quoted strings I was adding to the environment variables for whatever reason). Escaping the spaces with `\` seems to have resolved things.

**Comment by blueelvis** [comment]
@UpQuark - Thanks for that. Will test it out and then add to the post! This problem was coming up for me when I was trying to goof around from the SSH portal to debug stuff.
