### ISSUE TITLE
Images should be using PHP-FPM for better performance

### ISSUE THREAD

**Issue by hajekj** [appsvc/php#27]
Currently the PHP images are using the Apache 2 Handler which basically results in new PHP process being spawned. Nowadays, it would be much more efficient to use PHP-FPM to speed up the load times of applications and also reduce consumed memory, especially given, these are the sample images.

**Comment by nphmuller** [comment]
Note that this issue also exist in the php docker image when using the apache tag. I just made an issue about it:
https://github.com/docker-library/php/issues/681

**Comment by hajekj** [comment]
Aditionally, you can take a look here - I implemented it the similar way just with FPM and Apache - https://github.com/hajekj/hajekjnet-php/
The image consumes way less memory when running and the responses are about 50% faster.

**Comment by nphmuller** [comment]
Looks great. Already made my own dockerfile, but it looks like we took the exact same approach. :)

**Comment by patricklee2** [comment]
We are working on a php-fpm+nginx image: https://github.com/patricklee2/php/tree/nginx/7.2.5-nginx-fpm, it is still a work in progress, so don’t use it in prod.  You are is welcome to test it out and provide feedback.

**Comment by hajekj** [comment]
It looks really promising! Yet I still would like to see Apache2 FPM image available as well. Since I have a working one already (it could be ported to Alpine images to make it more compact), I could probably do a PR on the repo, what do you think?

**Comment by patricklee2** [comment]
We have no plans to support an apache+fpm blessed image.  Please make a request at https://feedback.azure.com/forums/169385-web-apps.

**Comment by patricklee2** [comment]
please use https://github.com/Azure-App-Service/nginx-fpm
