### ISSUE TITLE
SQL server ODBC

### ISSUE THREAD

**Issue by nopicnicc** [appsvc/php#34]
Hi, I'm trying to connect to an MS SQL server from php but I keep getting the following error:
SQLSTATE[IMSSP]: This extension requires the Microsoft ODBC Driver for SQL Server to communicate with SQL Server. Access the following URL to download the ODBC Driver for SQL Server for x64: https://go.microsoft.com/fwlink/?LinkId=163712

I'm guessing the php extensions are activated but there is a missing driver on the docker image.

I'm using php 7.2

Thank you,

Niklas

**Comment by nopicnicc** [comment]
Nothing? No comment from Microsoft?

**Comment by patricklee2** [comment]
see https://github.com/Azure-App-Service/php/pull/40
