### ISSUE TITLE
Initial directory is wrong using WebSSH 

### ISSUE THREAD

**Issue by ghost** [appsvc/php#37]
Logging in to Web SSH of from Azure Portal, `/home/site/wwwroot` is shown as initial directory.
But current directory is `/home` actually as following image.

![image](https://user-images.githubusercontent.com/37284286/51226675-d1aa5a00-1993-11e9-8177-7591378b87a1.png)

I confirmed that this issue occurs at [ruby runtime](https://github.com/Azure-App-Service/ruby), but not at [dotnetcore runtime](https://github.com/Azure-App-Service/dotnetcore)

**Comment by ghost** [comment]
I think `/bin/init_container.sh` has this issue.

Because current directory is `/home/site/wwwroot` before executing following command, 
Environment variable `PWD` is set to `/home/site/wwwroot`. 

```
eval $(printenv | sed -n "s/^\([^=]\+\)=\(.*\)$/export \1=\2/p" | sed 's/"/\\\"/g' | sed '/=/s//="/' | sed 's/$/"/' >> /etc/profile)
```

So `\w` in `PS1` is set to `/home/site/wwwroot` from `PWD`.

I think `cd /home` should be executed before above command in the `.sh`

**Comment by patricklee2** [comment]
fixed in https://github.com/Azure-App-Service/php-template/pull/3
